### ISSUE TITLE
No module named 'tzdata' error in Jenkins build phase

### ISSUE THREAD

**Issue by jorge-campo** [status-im/help.status.im#492]
The following Jenkins jobs:

- [dev-help.status.im](https://ci.infra.status.im/job/website/job/dev-help.status.im/)
- [help.status.im](https://ci.infra.status.im/job/website/job/help.status.im/)

Are failing with the following error:

```
09:24:56  [31mERROR    -  [0mError reading page 'index.md': Unknown timezone UTC
09:24:56  Traceback (most recent call last):
09:24:56    File "/usr/lib/python3.10/zoneinfo/_common.py", line 12, in load_tzdata
...
09:24:56  ModuleNotFoundError: No module named 'tzdata'
```

See the full error log attached next or on the [Jenkins site](https://ci.infra.status.im/job/website/job/dev-help.status.im/).

It seems python requires a new package to successfully build the `dev-help.status.im` and `help.status.im` sites. I don't know if we should add this to our `requirements.txt `or if it's something to include in the Jenkins job.

Using our `requirements.txt`, the site builds locally with no issues.

**Comment by jorge-campo** [comment]
```
9:43.291Z]   - status-communities/backup-your-community-key.md
05:39:43    - status-communities/change-the-channel-access-type.md
05:39:43    - status-communities/create-a-status-community.md
05:39:43    - status-communities/create-a-token-gated-channel.md
05:39:43    - status-communities/how-to-use-communities-your-quick-start-guide.md
05:39:43    - status-communities/leave-a-channel.md
05:39:43    - status-communities/understand-token-requirements-in-channels.md
05:39:43    - status-wallet/about-your-wallet-accounts-and-addresses.md
05:39:43    - status-wallet/how-to-use-status-wallet-your-quick-start-guide.md
05:39:43    - status-wallet/how-to-use-wallet-your-quick-start-guide.md
05:39:43    - status-wallet/import-your-wallet-funds-into-status-wallet.md
05:39:43    - status-wallet/send-crypto.md
05:39:43    - status-wallet/status-wallet-your-quick-start-guide.md
05:39:43    - using-status/add-remove-or-share-sticker-sets.md
05:39:43    - using-status/change-who-can-invite-you-to-group-chats.md
05:39:43    - using-status/customize-a-group-chat.md
05:39:43    - using-status/delete-a-chat-with-someone.md
05:39:43    - using-status/direct-messages.md
05:39:43    - using-status/enable-rich-link-previews-in-messages.md
05:39:43    - using-status/send-and-read-messages.md
05:39:43    - using-status/send-direct-messages-to-your-contacts.md
05:39:43    - using-status/understand-group-chats.md
05:39:43    - using-status/view-notifications-and-updates.md
05:39:43    - your-profile-and-preferences/about-keycard.md
05:39:43    - your-profile-and-preferences/back-up-and-secure-your-recovery-phrase.md
05:39:43    - your-profile-and-preferences/block-or-unblock-someone-in-status.md
05:39:43    - your-profile-and-preferences/create-and-use-additional-status-profiles.md
05:39:43    - your-profile-and-preferences/create-or-restore-your-status-profile-using-keycard.md
05:39:43    - your-profile-and-preferences/customize-your-status-profile.md
05:39:43    - your-profile-and-preferences/faq-status-keys-and-recovery-phrase.md
05:39:43    - your-profile-and-preferences/set-notification-exceptions.md
05:39:43    - your-profile-and-preferences/set-your-notification-exceptions.md
05:39:43    - your-profile-and-preferences/your-status-notification-guide.md
05:39:43    - your-profile-and-preferences/your-status-notifications-guide.md
05:39:43  [33mWARNING  -  [0mA relative path to 'getting-started/invite-friends-to-status' is included in the 'nav' configuration, which is not found in the documentation files
05:39:43  [33mWARNING  -  [0mA relative path to 'using-status/react-and-reply-to-messages' is included in the 'nav' configuration, which is not found in the documentation files
05:39:43  [33mWARNING  -  [0mA relative path to 'using-status/block-someone-in-status.md' is included in the 'nav' configuration, which is not found in the documentation files
05:39:43  [33mWARNING  -  [0mA relative path to 'your-profile-and-preferences/backup-and-secure-your-recovery-phrase' is included in the 'nav' configuration, which is not found in the documentation files
05:39:43  [33mWARNING  -  [0mA relative path to 'your-profile-and-preferences/block-or-unblock-someone-in-status' is included in the 'nav' configuration, which is not found in the documentation files
05:39:43  [33mWARNING  -  [0mA relative path to 'your-profile-and-preferences/log-out-of-status' is included in the 'nav' configuration, which is not found in the documentation files
05:39:43  [31mERROR    -  [0mError reading page 'index.md': Unknown timezone UTC
05:39:43  Traceback (most recent call last):
05:39:43    File "/usr/lib/python3.10/zoneinfo/_common.py", line 12, in load_tzdata
05:39:43      return importlib.resources.open_binary(package_name, resource_name)
05:39:43    File "/usr/lib/python3.10/importlib/resources.py", line 43, in open_binary
05:39:43      package = _common.get_package(package)
05:39:43    File "/usr/lib/python3.10/importlib/_common.py", line 66, in get_package
05:39:43      resolved = resolve(package)
05:39:43    File "/usr/lib/python3.10/importlib/_common.py", line 57, in resolve
05:39:43      return cand if isinstance(cand, types.ModuleType) else importlib.import_module(cand)
05:39:43    File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
05:39:43      return _bootstrap._gcd_import(name[level:], package, level)
05:39:43    File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
05:39:43    File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
05:39:43    File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
05:39:43    File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
05:39:43    File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
05:39:43    File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
05:39:43    File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
05:39:43  ModuleNotFoundError: No module named 'tzdata'
05:39:43  
05:39:43  During handling of the above exception, another exception occurred:
05:39:43  
05:39:43  Traceback (most recent call last):
05:39:43    File "/home/jenkins/.local/lib/python3.10/site-packages/babel/dates.py", line 247, in get_timezone
05:39:43      return zoneinfo.ZoneInfo(zone)
05:39:43    File "/usr/lib/python3.10/zoneinfo/_common.py", line 24, in load_tzdata
05:39:43      raise ZoneInfoNotFoundError(f"No time zone found with key {key}")
05:39:43  zoneinfo._common.ZoneInfoNotFoundError: 'No time zone found with key UTC'
05:39:43  
05:39:43  The above exception was the direct cause of the following exception:
05:39:43  
05:39:43  Traceback (most recent call last):
05:39:43    File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
05:39:43      return _run_code(code, main_globals, None,
05:39:43    File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
05:39:43      exec(code, run_globals)
05:39:43    File "/home/jenkins/.local/lib/python3.10/site-packages/mkdocs/__main__.py", line 301, in <module>
05:39:43      cli()
05:39:43    File "/home/jenkins/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
05:39:43      return self.main(*args, **kwargs)
05:39:43    File "/home/jenkins/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
05:39:43      rv = self.invoke(ctx)
05:39:43    File "/home/jenkins/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
05:39:43      return _process_result(sub_ctx.command.invoke(sub_ctx))
05:39:43    File "/home/jenkins/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
05:39:43      return ctx.invoke(self.callback, **ctx.params)
05:39:43    File "/home/jenkins/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
05:39:43      return __callback(*args, **kwargs)
05:39:43    File "/home/jenkins/.local/lib/python3.10/site-packages/mkdocs/__main__.py", line 250, in build_command
05:39:43      build.build(cfg, dirty=not clean)
05:39:43    File "/home/jenkins/.local/lib/python3.10/site-packages/mkdocs/commands/build.py", line 308, in build
05:39:43      _populate_page(file.page, config, files, dirty)
05:39:43    File "/home/jenkins/.local/lib/python3.10/site-packages/mkdocs/commands/build.py", line 177, in _populate_page
05:39:43      page.markdown = config.plugins.run_event(
05:39:43    File "/home/jenkins/.local/lib/python3.10/site-packages/mkdocs/plugins.py", line 520, in run_event
05:39:43      result = method(item, **kwargs)
05:39:43    File "/home/jenkins/.local/lib/python3.10/site-packages/mkdocs_git_revision_date_localized_plugin/plugin.py", line 206, in on_page_markdown
05:39:43      revision_dates = self.util.get_date_formats_for_timestamp(last_revision_timestamp, locale=locale, add_spans=True)
05:39:43    File "/home/jenkins/.local/lib/python3.10/site-packages/mkdocs_git_revision_date_localized_plugin/util.py", line 196, in get_date_formats_for_timestamp
05:39:43      date_formats = self._date_formats(
05:39:43    File "/home/jenkins/.local/lib/python3.10/site-packages/mkdocs_git_revision_date_localized_plugin/util.py", line 68, in _date_formats
05:39:43      tzinfo=get_timezone("UTC")
05:39:43    File "/home/jenkins/.local/lib/python3.10/site-packages/babel/dates.py", line 251, in get_timezone
05:39:43      raise LookupError(f"Unknown timezone {zone}") from exc
05:39:43  LookupError: Unknown timezone UTC
```

**Comment by jakubgs** [comment]
That's literally the purpose of [`requirements.txt`](https://github.com/status-im/help.status.im/blob/develop/requirements.txt). To define python dependencies.

If it works locally it probably just means your local system has that module installed. That has no bearing on the CI builds.

**Comment by jorge-campo** [comment]
Thanks, @jakubgs -- Adding the `pytz` Python module to `requirements.txt` fixed the issue.

Oddly enough, this module was not on my computer either (but clearly, something else was providing timezone support). This is my local run:

```
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pytz==2021.1
  Downloading pytz-2021.1-py2.py3-none-any.whl (510 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.8/510.8 kB 3.9 MB/s eta 0:00:00
```
